config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :home
  resources :students
  resources :courses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :student_courses

  validates :name, presence: true, uniqueness: true
  validates :credit, presence: true, format: { with: /\A\d+\z/, message: "Integer only. No sign allowed." }
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :student_courses

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true, format: { with: /\A\d+\z/, message: "Integer only. No sign allowed." }

  def gpa
    student_courses.average(:grade_point).to_f.round(2)
  end

  def total_credit
    student_courses.joins(:course).sum(:credit)
  end

end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course

  validates :student_id, presence: true
  validates :course_id, presence: true
  validates :grade_point, presence: true
  validates_inclusion_of :grade_point, :in => 0.0..4.0

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course::all
  end

  def new
    @course = Course.new
  end
  

  def create
    @course = Course.new(course_params)

    if @course.save
      flash[:notice] = 'Course was successfully created.'
      redirect_to courses_path
    else
      render :new
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update(course_params)
      flash[:notice] = 'Course updated!'
      redirect_to courses_path
    else
      flash[:error] = 'Failed to edit course!'
      render :edit
    end
  end

  def destroy
    @course = Course.find(params[:id])
    if @course.delete
      flash[:notice] = 'Course deleted!'
      redirect_to courses_path
    else
      flash[:error] = 'Failed to delete this course!'
      render :destroy
    end
  end

  private

  def course_params
    params.require(:course).permit(
      :name,
      :credit
    )
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @students = Student.all
  end

  def show
    @student_courses = StudentCourse.where(student_id: params[:id])
  end

  def new
    @student_course = StudentCourse.new
  end

  def create
    @student_course = StudentCourse.new(student_course_params)
    if @student_course.save
      flash[:notice] = 'Student course was successfully created.'
      redirect_to home_path(@student_course.student_id)
    else
      render :new
    end
  end

  def edit
    @student_course = StudentCourse.find(params[:id])
  end

  def update
    @student_course = StudentCourse.find(params[:id])
    if @student_course.update(student_course_params)
      flash[:notice] = 'Student course updated!'
      redirect_to home_path(@student_course.student_id)
    else
      flash[:error] = 'Failed to edit student course!'
      render :edit
    end
  end

  def destroy
    @student_course = StudentCourse.find(params[:id])
    if @student_course.delete
      flash[:notice] = 'Student course deleted!'
      redirect_to home_path(@student_course.student_id)
    else
      flash[:error] = 'Failed to delete this student course!'
      render :destroy
    end
  end

  private
  
  def student_course_params
    params.require(:student_course).permit(:student_id, :course_id, :grade_point)
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:notice] = 'Student was successfully created.'
      redirect_to students_path
    else
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      flash[:notice] = 'Student updated!'
      redirect_to students_path
    else
      flash[:error] = 'Failed to edit student!'
      render :edit
    end
  end

  def destroy
    @student = Student.find(params[:id])
    if @student.delete
      flash[:notice] = 'Student deleted!'
      redirect_to students_path
    else
      flash[:error] = 'Failed to delete this student!'
      render :destroy
    end
  end

  private
  
  def student_params
    params.require(:student).permit(:last_name, :first_name, :age)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/edit.html.erb
<div class="container p-5 my-5">
  <%= form_for @course, url: {action: :update} do |f| %>
    <% if @course.errors.any? %>
      <h2>Errors:</h2>
      <ul>
        <% @course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="mb-3">
      <label for="name" class="form-label">Course Name</label>
      <%= f.text_field :name, maxlength: 100, class: 'form-control', placeholder: 'Course name' %>
    </div>
    <div class="mb-3">
      <label for="credit" class="form-label">Credit</label>
      <%= f.number_field :credit, in: 1..5, step: 1, class: 'form-control', placeholder: 'Credit' %>
    </div>
    <%= link_to 'Back', { controller: 'courses', action: 'index'}, class: 'btn btn-light' %>
    <button type="submit" class="btn btn-primary">Save</button>
  <% end %>
</div>

app/views/courses/index.html.erb
<div class="container p-5 my-5">
  <div class="card">
    <div class="card-header">
      Courses
      <%= link_to '+', new_course_path, class: 'btn btn-outline-success' %>
    </div>
    <div class="card-body">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Credit</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @courses.each do |course| %>
          <tr>
            <th scope="row"><%= course.id %></th>
            <td><%= course.name %></td>
            <td><%= course.credit %></td>
            <td>
              <%= link_to 'Edit', edit_course_path(course) %>
              <%= link_to 'Delete', course_path(course), method: :delete %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/courses/new.html.erb
<div class="container p-5 my-5">
  <%= form_for @course, url: {action: :create} do |f| %>
    <% if @course.errors.any? %>
      <h2>Errors:</h2>
      <ul>
        <% @course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="mb-3">
      <label for="name" class="form-label">Course Name</label>
      <%= f.text_field :name, maxlength: 100, class: 'form-control in-valid', placeholder: 'Course name' %>
    </div>
    <div class="mb-3">
      <label for="credit" class="form-label">Credit</label>
      <%= f.number_field :credit, in: 1..5, step: 1, class: 'form-control', placeholder: 'Credit' %>
    </div>
    <%= link_to 'Back', { controller: 'courses', action: 'index'}, class: 'btn btn-light' %>
    <button type="submit" class="btn btn-primary">Add</button>
  <% end %>
</div>

app/views/home/edit.html.erb
<div class="container p-5 my-5">
  <%= form_for @student_course, url: {action: :update} do |f| %>
    <% if @student_course.errors.any? %>
      <h2>Errors:</h2>
      <ul>
        <% @student_course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="mb-3">
      <label for="student_name" class="form-label">Student</label>
      <%= f.collection_select :student_id, Student.order(:first_name), :id, :first_name, {},  {class: 'form-select'} %>
    </div>
    <div class="mb-3">
      <label for="course_name" class="form-label">Course</label>
      <%= f.collection_select :course_id, Course.order(:name), :id, :name, {},  {class: 'form-select'} %>
    </div>
    <div class="mb-3">
      <label for="grade_point" class="form-label">Grade Point</label>
      <%= f.number_field :grade_point, in: 0.0..4.0, step: 0.1, class: 'form-control', placeholder: 'Enter between 0 to 4' %>
    </div>
    <%= link_to 'Back', { controller: 'home', action: 'show', id: @student_course.student_id}, class: 'btn btn-light' %>
    <button type="submit" class="btn btn-primary">Save</button>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="container p-5 my-5">
  <div class="card">
    <div class="card-header">
      Student GPA list
    </div>
    <div class="card-body">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Student Name</th>
            <th scope="col">Total Credit</th>
            <th scope="col">GPA</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @students.each do |student| %>
          <tr>
            <th scope="row"><%= student.id %></th>
            <td><%= student.first_name %></td>
            <td><%= student.total_credit %></td>
            <td><%= student.gpa %></td>
            <td>
              <%= link_to 'Show', home_path(student) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/home/new.html.erb
<div class="container p-5 my-5">
  <%= form_for @student_course, url: {action: :create} do |f| %>
    <% if @student_course.errors.any? %>
      <h2>Errors:</h2>
      <ul>
        <% @student_course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="mb-3">
      <label for="student_name" class="form-label">Student</label>
      <%= f.collection_select :student_id, Student.order(:first_name), :id, :first_name, {},  {class: 'form-select'} %>
    </div>
    <div class="mb-3">
      <label for="course_name" class="form-label">Course</label>
      <%= f.collection_select :course_id, Course.order(:name), :id, :name, {},  {class: 'form-select'} %>
    </div>
    <div class="mb-3">
      <label for="grade_point" class="form-label">Grade Point</label>
      <%= f.number_field :grade_point, in: 0.0..4.0, step: 0.1, class: 'form-control', placeholder: 'Enter between 0 to 4' %>
    </div>
    <%= link_to 'Back', { controller: 'home', action: 'index'}, class: 'btn btn-light' %>
    <button type="submit" class="btn btn-primary">Add</button>
  <% end %>
</div>

app/views/home/show.html.erb
<div class="container p-5 my-5">
  <div class="card">
    <div class="card-header">
      Student Transcript list
      <%= link_to '+', new_home_path, class: 'btn btn-outline-success' %>
    </div>
    <div class="card-body">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Student Name</th>
            <th scope="col">Course Name</th>
            <th scope="col">Course Credit</th>
            <th scope="col">Grade Point</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @student_courses.each do |sc| %>
          <tr>
            <th scope="row"><%= sc.id %></th>
            <td><%= sc.student.first_name %></td>
            <td><%= sc.course.name %></td>
            <td><%= sc.course.credit %></td>
            <td><%= sc.grade_point %></td>
            <td>
              <%= link_to 'Edit', edit_home_path(sc) %>
              <%= link_to 'Delete', home_path(sc), method: :delete %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="card-footer">
      <%= link_to '<- Return Student Transcript list', { controller: 'home', action: 'index' }, class: 'btn btn-link' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">StudentApp</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link <%= 'active' if params[:controller] == 'home' %>" aria-current="page" href="/home">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link <%= 'active' if params[:controller] == 'students' %>" aria-current="page" href="/students">Students</a>
            </li>
            <li class="nav-item">
              <a class="nav-link <%= 'active' if params[:controller] == 'courses' %>" aria-current="page" href="/courses">Courses</a>
            </li>
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<div class="container p-5 my-5">
  <%= form_for @student, url: {action: :update} do |f| %>
    <% if @student.errors.any? %>
      <h2>Errors:</h2>
      <ul>
        <% @student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="mb-3">
      <label for="last_name" class="form-label">Last Name</label>
      <%= f.text_field :last_name, maxlength: 100, class: 'form-control in-valid', placeholder: 'Last Name' %>
    </div>
    <div class="mb-3">
      <label for="first_name" class="form-label">First Name</label>
      <%= f.text_field :first_name, maxlength: 100, class: 'form-control in-valid', placeholder: 'First Name' %>
    </div>
    <div class="mb-3">
      <label for="age" class="form-label">Age</label>
      <%= f.number_field :age, in: 1..100, step: 1, class: 'form-control', placeholder: 'Age' %>
    </div>
    <%= link_to 'Back', { controller: 'students', action: 'index'}, class: 'btn btn-light' %>
    <button type="submit" class="btn btn-primary">Save</button>
  <% end %>
</div>

app/views/students/index.html.erb
<div class="container p-5 my-5">
  <div class="card">
    <div class="card-header">
      Students
      <%= link_to '+', new_student_path, class: 'btn btn-outline-success' %>
    </div>
    <div class="card-body">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Last name</th>
            <th scope="col">First name</th>
            <th scope="col">Age</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @students.each do |student| %>
          <tr>
            <th scope="row"><%= student.id %></th>
            <td><%= student.last_name %></td>
            <td><%= student.first_name %></td>
            <td><%= student.age %></td>
            <td>
              <%= link_to 'Edit', edit_student_path(student) %>
              <%= link_to 'Delete', student_path(student), method: :delete %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/students/new.html.erb
<div class="container p-5 my-5">
  <%= form_for @student, url: {action: :create} do |f| %>
    <% if @student.errors.any? %>
      <h2>Errors:</h2>
      <ul>
        <% @student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="mb-3">
      <label for="last_name" class="form-label">Last Name</label>
      <%= f.text_field :last_name, maxlength: 100, class: 'form-control in-valid', placeholder: 'Last Name' %>
    </div>
    <div class="mb-3">
      <label for="first_name" class="form-label">First Name</label>
      <%= f.text_field :first_name, maxlength: 100, class: 'form-control in-valid', placeholder: 'First Name' %>
    </div>
    <div class="mb-3">
      <label for="age" class="form-label">Age</label>
      <%= f.number_field :age, in: 1..100, step: 1, class: 'form-control', placeholder: 'Age' %>
    </div>
    <%= link_to 'Back', { controller: 'students', action: 'index'}, class: 'btn btn-light' %>
    <button type="submit" class="btn btn-primary">Add</button>
  <% end %>
</div>